version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: dev
  reviewers:
  - the-code-monkey
  assignees:
  - the-code-monkey
  ignore:
  - dependency-name: copy-webpack-plugin
    versions:
    - ">= 6.0.a"
    - "< 6.1"
