version: 2
registries:
  npm-registry-npm-pkg-github-com-aw-web-design:
    type: npm-registry
    url: https://npm.pkg.github.com/aw-web-design
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_AW_WEB_DESIGN_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: dev
  versioning-strategy: increase
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: css-loader
    versions:
    - 5.2.3
  - dependency-name: ts-loader
    versions:
    - 9.0.0
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: next
    versions:
    - 10.1.0
  registries:
  - npm-registry-npm-pkg-github-com-aw-web-design
