version: 2.1
  
orbs:
  node: circleci/node@2.0.3
  
machine:
  environment:
    CACHE_KEY: dependency-cache-{{ checksum "yarn.lock" }
  pre:
    - mkdir ~/.yarn-cache
    
dependencies:
  cache_directories:
    - ~/.yarn-cache

workflows:
  version: 2
  commit:
    jobs:
      - test
      - build:
          requires:
            - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    environment:
      CACHE_KEY: dependency-cache-{{ checksum "yarn.lock" }
    steps:
      - checkout:
          path: ~/project
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - save_cache:
          key: ${CACHE_KEY}
          paths:
            - ~/.cache/yarn
  build:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    environment:
      CACHE_KEY: dependency-cache-{{ checksum "yarn.lock" }
    steps:
      - restore_cache:
          key: ${CACHE_KEY}
      - run: yarn build
      - save_cache:
          key: ${CACHE_KEY}
          paths:
            - ~/.cache/yarn
            - packages/app
  deploy:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    environment:
      CACHE_KEY: dependency-cache-{{ checksum "yarn.lock" }
    steps:
      - restore_cache:
          key: ${CACHE_KEY}
      - run: sudo apt install rsync
