version: 2.1
  
orbs:
  node: circleci/node@2.0.3

workflows:
  version: 2
  commit:
    jobs:
      - test
      - build:
          requires:
            - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - packages/app
  deploy:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: sudo apt install rsync
