version: 2.1

orbs:
  node: circleci/node@1.1

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/with-cache:
          steps:
            - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test
  deploy:
    executor:
      name: node/default
      tag: '10.4'
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/with-cache:
          steps:
            - run: yarn
      - run: sudo apt install rsync
      - run: yarn lint
      - run: yarn test
      - run: yarn build
