version: 2.1
  
orbs:
  node: circleci/node@2.0.3

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - run: yarn
      - run: cd ./node_modules/@orchard && ls -la
      - run: yarn lint
      - run: yarn build
      - run: yarn test
  deploy:
    executor:
      name: node/default
      tag: '12.16'
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - run: yarn
      - run: sudo apt install rsync
      - run: yarn lint
      - run: yarn test
      - run: yarn build
